### ISSUE TITLE
Brew upgrade get stuck in removing…

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#1208]
This is not exactly a bug report since the problem **seems to be upstream in Homebrew Core**, but I think it's worth it to have an issue in here about it since —I guess— a lot of people that uses this tap is using also R and Cairo. Either from core or from @sethrfore [tap](https://github.com/sethrfore/homebrew-r-srf). 

The issue is simple, when you run a `brew upgrade` and you upgrade some packages brew usually get stuck at the end of the process in `removing…`. I don't really know what is the exact issue and if it's cause by Seth tap, for the Core R and Cairo formulae or just Ruby has some problems with those two formulae. The issue isn't consistent, and at least in my case is not arising every time, but lately it has been more recurrent. 

![](https://aws1.discourse-cdn.com/standard17/uploads/brew/original/2X/c/c87e33589c5a16389d67ddbfe221555d008075ab.jpeg)

I think it's wise that if you have the same problem you report it in this [post](https://discourse.brew.sh/t/brew-upgrade-get-stuck-in-removing/4915) in [discourse.brew.sh](https://discourse.brew.sh/) so maintainers are aware of the issue and that more people is having it. 

Why don't report it on brew repository? Well they have to strict rules for what it should be reported there. 😅 

EDIT: grammar and typos correction and expanding a little bit the info.

**Comment by fjperini** [comment]
@luispuerto It is something that I have also noticed.

**Comment by Wicky2k8** [comment]
Think this is tied to the [same issue I see](https://github.com/OSGeo/homebrew-osgeo4mac/issues/1199), which eventually leads to a broken dependency issue. It does seem somehow linked to this tap, as when all osgeo formula are uninstalled the issue seems to goes away.

**Comment by luispuerto** [comment]
@Wicky2k8 ad you can see in the Brew forum thread, @sethrfore is also experiencing the issue and I think he doesn't have any osgeo-formulae installed. Seems that is more related to homebrew in general, or the R and Cario formulae. 

I really think that the issue you reported #1199 it's independent and I've also experienced something similar before. 

Perhaps some issues are more noticeable with osgeo related formule because they have tons of dependencies.

**Comment by Wicky2k8** [comment]
@luispuerto 
Ya, think you might be right about the issue relating to either the r packages or homebrew itself, I tried removing the r formula ignoring qgis' dependency (I've been using the core r as well as the cask). The one upgrade I've done after went fine, but as you've probably experienced it's intermittent so hard to know till I try a few times. (However it seems more common for larger upgrades covering more formula, and this recent one upgraded ~20, so that's a good sign.) Could be an issue with things dependent on r, as for me osgeo formulas are the only ones which are.

Think the issue is the same though, but the broken dependency part might be unrelated. The delay/hanging we're all experiences actually seems caused by a broken dependency check being forced after the upgrade, which can take forever, not the removing step per-say (running with debug breaks this out, otherwise it's hidden.)
"==> Checking dependents for broken library links."

Whether it actually finds broken dependencies probably varies between setups and is probably related to something specific to mine, but think it's this process which eats up time either way.

**Comment by sethrfore** [comment]
Just to clarify, I do have quite a few osgeo-formulae installed but I guess I hadn't yet contributed to the conversation since all I know is detailed in the homebrew discourse [post](https://discourse.brew.sh/t/brew-upgrade-get-stuck-in-removing/4915) referenced earlier in the thread. That said, I've nothing new or any beneficial insights to add.

**Comment by Wicky2k8** [comment]
Update on this, even with r and cairo uninstalled I get the same issue on occasion. Do think it has something to do with osgeo at this point, though not sure why it would be causing this..

**Comment by luispuerto** [comment]
@Wicky2k8 do you have seth's tap un tapped?

**Comment by Wicky2k8** [comment]
Ya, I just use the core r formula (or was using at least)

**Comment by miguelangelperg** [comment]
`brew upgrade` gets stuck trying to update  _osgeo-postgresql@10_  version.

**Comment by grischard** [comment]
https://discourse.brew.sh/t/brew-upgrade-get-stuck-in-removing/4915/27 seems to be the same issue.

**Comment by alazarolop** [comment]
@luispuerto are you still having this issue or it's fixed with recent updates?

**Comment by luispuerto** [comment]
@alazarolop it's fixed, now you that you've mentioned it.
