### ISSUE TITLE
PostgreSQL version collision with homebrew

### ISSUE THREAD

**Issue by mzagaja** [OSGeo/homebrew-osgeo4mac#1284]
**Please answers the following**

I've... 
- I read
	- [ ] the [reporting issues](https://github.com/OSGeo/homebrew-osgeo4mac/docs/reporting-issues) <--this link is broken
	- [ ] the [troubleshooting](https://github.com/OSGeo/homebrew-osgeo4mac/docs/troubleshooting) <---this link is also broken
- [X] I checked the documentation and found no answer
- [X] I tried to install after following the suggestions
- [X] I am running the latest version (`brew update` twice?)
- [X] I checked to make sure that this issue has not already been filed
- [ ] I uploaded logs: `brew gist-logs formula` <---N/A

**Describe the bug**

As a homebrew user I have to maintain an install of the homebrew version of postgresql side by side with the osgeo-postgresql because both of these are dependencies to software that I use. Generally I have been successful in having these both installed but recently osgeo-postgresql made Postgres 12 available. The homebrew version of Postgres is still at version 11.5, thus causing Postgres to break. My system was unable to connect to Postgres because the linked command line tools were at version 12.

**To Reproduce**

1. Install osgeo and homebrew postgres side by side
2. `brew services start postgresql` (the homebrew version)
3. make sure the osgeo version is not started
4. Note that you cannot connect to homebrew postgresql with `psql`.

**Expected behavior**

In a world where I am required to run both versions side-by-side, I would expect the current HEAD versions of osgeo-postgresql and homebrew's version of postgresql to work together. osgeo-postgresql should not be pulled down automatically if it will break existing installs. Either the maintainers of homebrew postgresql should keep pace with this repo, or this repo should hold back if a version update will break things on a system with concurrent installs.

**Comment by 3nids** [comment]
more generally, to me the duplication of the formulas is a nightmare to handle. Postgresql and PyQt5/sip are the ones which are the most painful.
While the idea of duplicating formulas might be acceptable, it is a very difficult for who is not very (VERY) familiar with Homebrew.

**Comment by alazarolop** [comment]
I'm sorry for the inconveniences. Apart from just starting the core `postgresql` formula, have you tried to unlink `osgeo-postgresql` and link the core version? If you aren't using `osgeo-postgis` I think you could fix it that way.

**Comment by mzagaja** [comment]
Yeah that does end up working to "fix" it, so maybe worth documenting or providing additional warning for folks that also end up in the same situation.

**Comment by alazarolop** [comment]
@mzagaja I’m glad it worked. I would say the previous situation wasn’t stable as you were using two different formulas for the same service, one for the database engine and one for the command line tools. So it wasn’t a proper fix rather than understanding how homebrew works in a case like this. 

I think it would be a good idea to warn about it in the formula documentation too.

**Comment by tmepple** [comment]
I have previously installed PostgreSQL and Postgis using the core formulas, the [Petere tap](https://github.com/petere/homebrew-postgresql), and this osgeo4mac formula.  All of these methods work but can cause significant pain when upgrading due to all the dependencies and the uneven timing of when new versions of each component is released by each packager.  This issue compounds when you want to run several PostgreSQL instances side-by-side to support different projects as stated by the OP.

I did a lot of testing attempting to upgrade to PG 12.1, Postgis 3, and GDAL 3.0.2 and found it to be much easier to just install https://postgresapp.com (which bundles latest Postgis) and GDAL + plugins from osgeo4mac. It all now works great.

The osgeo4mac GDAL formula installs osgeo-postgresql which is fine since you can keep it unlinked and not running.  Also by putting the postgres.app CLI tools at the end of your PATH you default to using the osgeo GDAL CLI tools.  Hope this helps!

**Comment by 3nids** [comment]
I was about to post the same. I finally looked for an alternative solution after loosing once more time at trying to get Postgres running correctly. I ended up on Postgres.app for the first time and it proved to be very convenient since it packages postgis.
I wonder if it wouldn't be better to only provide the client as an osgeo formula?
I guess there are not so many people using it as a DB and rather rely on a docker or postgres.app.
