### ISSUE TITLE
QGIS-28 Library not loaded: /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib

### ISSUE THREAD

**Issue by peteWT** [OSGeo/homebrew-osgeo4mac#134]
Hi,

Im on OSX El Capitan (10.11.4). Just upgraded a bunch of packages and qgis-28 now won't open:

`Dyld Error Message:
  Library not loaded: /usr/local/opt/qscintilla2/lib/libqscintilla2.11.dylib
  Referenced from: /usr/local/opt/qgis-28/QGIS.app/Contents/MacOS/QGIS
  Reason: image not found`

qscintilla2 is this:

`
$ brew info qscintilla2
qscintilla2: stable 2.9.2 (bottled)
Port to Qt of the Scintilla editing component
https://www.riverbankcomputing.com/software/qscintilla/intro
/usr/local/Cellar/qscintilla2/2.8.4 (128 files, 5.7M)
  Poured from bottle
/usr/local/Cellar/qscintilla2/2.9.1 (129 files, 6.2M)
  Poured from bottle
/usr/local/Cellar/qscintilla2/2.9.2 (129 files, 6M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qscintilla2.rb
==> Dependencies
Required: pyqt ✔
==> Options
--with-python3
	Build with python3 support
--without-plugin
	Skip building the Qt Designer plugin
--without-python
	Skip building the Python bindings
`

Thanks in advance!

Peter

**Comment by dakcarto** [comment]
Hi @peteWT,

Thanks for reporting. You need to rebuild `qgis-28` (bottles are currently incompatible and have been commented out, see 212753f ). Alternatively, if you are going to build from source, try the `qgis-214` formula instead.

**Comment by peteWT** [comment]
Thanks Larry,

I'm afraid I'm new enough to homebrew that I don't know exactly what that
means. I this what 'rebuild means:

$ brew install --build-from-source qgis-28

**Comment by dakcarto** [comment]
You are using `qgis-28`, which had pre-built binaries as "bottles" that were installed instead of compiling from source code. If you try doing `brew reinstall qgis-28` or `brew install qgis-214` both will now only build from source, which should remedy your issue.

The issue stems from the fact you changed the linked-to dynamic library, specifically you upgraded `libqscintilla2`, thereby removing (really just unlinking) the previous version that the bottle was built against. Recompiling from scratch will link to whatever is currently installed, though it will take considerably longer.

**Comment by peteWT** [comment]
Thanks @dakcarto I just went with `qgis-214` and after unlinking the `ghostscript` tools MacTeX installs,  it built and is working well.

Haven't tried to `pdflatex` yet...
