### ISSUE TITLE
'HDF4' unsupported format in GDAL

### ISSUE THREAD

**Issue by ankitrao22** [OSGeo/homebrew-osgeo4mac#1370]
I am currently working on MODIS land cover product MCD12Q1 to understand the land cover changes in the past 10 years. The retrieved files from the MODIS are in hdf4 format with sinusoidal grid system.
In order to convert the projection to wgs84 (equidistant cylindrical) , I installed GDAL with the help of homebrew. I have all the other raster drivers installed including netcdf, Geotiff, hdf5 and others.

I want to have hdf4 raster driver compiled to my installed gdal.

My work will be paced up if anyone can help me out with this problem.

Thank you

Ankit
IISER Mohali

**Comment by alazarolop** [comment]
Hi Ankit, 

The issue have been fixed in this commit https://github.com/OSGeo/homebrew-osgeo4mac/commit/7af89e6c756cc74f136945cbc21ac78060dcc078. However, because of a dependency from core, some formulas need to be rebuild in order to release the upgrade and it's going to take some time. If you are in a hurry you can temporally workaround this by locally editing `osgeo-gdal` formula until new changes are merged. 

In your terminal: 
`brew edit osgeo-gdal`

Uncomment the following lines (delete #): 

85: depends_on "osgeo-hdf4"
166: "--with-hdf4=#{Formula["osgeo-hdf4"].opt_prefix}",
302: inreplace "configure", "-ldf", "-lhdf"

Then:
`brew install osgeo-gdal ---build-from-source`

If not, just wait until everything is finished.

**Comment by alazarolop** [comment]
@ankitrao22 Done https://github.com/OSGeo/homebrew-osgeo4mac/commit/7af89e6c756cc74f136945cbc21ac78060dcc078

**Comment by ankitrao22** [comment]
thank you @alazarolop 
I am working on this. 
Will inform if all goes good. 

Thank you very much for the assistance

**Comment by ankitrao22** [comment]
@alazarolop 
Gdal is working with hdf4 files 
Thank you for your efforts and suggestions. 

Ankit 
IISER Mohali
