### ISSUE TITLE
arm64 native bottle

### ISSUE THREAD

**Issue by n0rdlicht** [OSGeo/homebrew-osgeo4mac#1405]
**Is your feature request related to a problem? Please describe.**

Although some underlying libraries are not yet ready (e.g. gdal), the homebrew team is [currently](https://github.com/Homebrew/brew/issues/10152) entering the official arm64 rollout to support Apple Silicon Macs. Is support for arm64 bottles planned once the osgeo stack is ready?

**Describe the solution you'd like**

Fully arm64 native osgeo bottles.

**Describe alternatives you've considered**

Running a seperate x86 homebrew installation and using x86 osgeo bottles under rosetta 2.

**Additional context**

n/a

**Comment by alazarolop** [comment]
Thanks for bringing up this topic. Not at this moment. The idea is take advantage of formulas already present at core (e.g. `gdal`) and define complementary formulas to build the software instead of bottles. 

The main reason for that is the current dependency on some core formulas. It's been suggested to create a system to automatically rebuild tap bottles depending on these core formulas, but it hasn't been tackle yet.
