### ISSUE TITLE
Using osgeo4mac's gdal2 with homebrew core's postgis

### ISSUE THREAD

**Issue by pjduplooy** [OSGeo/homebrew-osgeo4mac#185]
Hi guys

This is not an issue per se, but would like to know if I can use osgeo4mac's gdal2, and compile homebrew-core' postgis with it in stead if gdal?

Or can I have both gdal1 and gdal2?

Pieter

**Comment by nextstopsun** [comment]
Same question here. Maybe postgis formula should move to osgeo4mac?

**Comment by dakcarto** [comment]
@pjduplooy and @nextstopsun thanks for commenting. Yes, this is a concern for a full geospatial stack. Since `postgis` is generally not linked against, and `gdal2`(keg-only) and `gdal`(v1.11.x) can coexist in the same Homebrew prefix, it should be possible to add `gdal2` as an optional install to `postgis`.

You could just hack the `postgis` and add `depends_on "osgeo/osgeo4mac/gdal2"` (instead of `gdal`) and see what happens when you reinstall `postgis` from source.

However, this should probably wait until this repo is migrated to the new Homebrew-geospatial tap. At which time, there would be less concerns by Homebrew users about a non-Homebrew tap dependency for a core formula. Whether `postgis` and other GIS formulae are migrated to Homebrew-geospatial is another issue entirely.

**Comment by joshmarcus** [comment]
I just hit this question, and resolved my own issue by installing postgis without postgis raster support with the ` --without-gdal` option.

```
brew install postgis --without-gdal
```

**Comment by luisspuerto** [comment]
@dakcarto I'm a little bit puzzle... 

I have problems having gdal and gdal2 at the same time because R is picking all the time the gdal intall since gdal2 is keg-only. 

should just have the two and force link gdal2 and ignore the suggestions in `brew doctor`? 
does postgis work correctly if i force link gdal2? 

Thanks! 
PS/ If you know any way to fix the problem in R, i would be also happy to hear.
