### ISSUE TITLE
Update SAGA to 3.0

### ISSUE THREAD

**Issue by cablebox** [OSGeo/homebrew-osgeo4mac#190]
The current version on brew is 2.2.2, however the most recent version available is 3.0.

I attempted compiling manually, however I wasn't able do so successfully.

**Comment by dakcarto** [comment]
The current version of 2.2.2 is held back because higher versions are incompatible with Processing framework algorithms in QGIS. With the jump in major version to 3.0, this would allow two separate formulae to coexist, with maybe a `saga-gis3` or `saga-gis2` formulae made keg-only.

Please feel free to submit a pull request for a new or updated formula.

**Comment by nickrobison** [comment]
@cablebox With #378 we recently updated our `saga-gis` formula to the latest version (6.3.0). We also updated `saga-gis-lts` to work correctly with `qgis2`, feel free to give them a spin and see if they work for you.

Cheers!
