### ISSUE TITLE
"--with-oracle" build succeeds, but adding oracle db connection crashes qgis

### ISSUE THREAD

**Issue by chrismarx** [OSGeo/homebrew-osgeo4mac#200]
Hi,

When I try to make a connection (either by adding a layer or adding a db connection), qgis hangs for a long time and then crashes. I added error logging as mentioned here (http://gis.stackexchange.com/questions/84790/where-does-qgis-write-its-error-log-messages) and all I got in the error log is:

QOCISpatialDriver: unable to create environment

I guessed that maybe I was entering the connection information improperly somehow, but I just installed the latest version of osgeo4w's version of qgis on a window virtual machine, running on the same computer, and entered the exact same connection information, and it worked perfectly-

**Comment by jmunowitch** [comment]
I am also struggling with this issue as well.

**Comment by dakcarto** [comment]
Hi @chrismarx and @jmunowitch, thanks for reporting! Apologies for the long delay on this.

I've finally gotten a chance to rework the `oracle-client-sdk` formula in fb92ed0 and 6a75d23, and have successfully tested with `qgis2`, `qgis3-dev` and `gdal2-oracle`, using both Basic and BasicLite instant clients. Please try if you have the time.

---

Side note: the current version of the [Oracle Instant Client for macOS](http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html) is **12.2.0.1.0**, while the formula is still at **12.1.0.2** (last updated 7/5/2017). The reason for this is that those client libs are pre-built binaries; so, the macOS minimum version and SDK they were built against have to be taken into consideration.

`otool -l instantclient_12.1.0.2.0-basiclite/libclntsh.dylib.12.1` output:
```
...
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 10.9
...
```

`otool -l instantclient_12.1.0.2.0-basiclite/libclntsh.dylib.12.1` output:
```
...
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.11
      sdk 10.11
...
```

Keeping the macOS 10.9 and 10.10 support for now is prudent, since Homebrew still supports 10.10 (Yosemite) on many formulae.

**Comment by jmunowitch** [comment]
@dakcarto: I tested this, and it is working with 2.18.14 (qgis2). Thanks! this works well now.
