### ISSUE TITLE
GDAL missing dependency PCRE?

### ISSUE THREAD

**Issue by warpedgeoid** [OSGeo/homebrew-osgeo4mac#226]
Is it possible that GDAL2 is missing a dependency on PCRE? I get the following on a clean Sierra install after having just installed gdal2 from this tap. Is this because gdal2 is keg-only and I'm modding my path to access the command-line tools instead of installing the older version of gdal?

`
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/opt/gdal2/bin/ogr2ogr
  Reason: image not found
`

Running `brew install pcre` fixes the issue.

**Comment by dakcarto** [comment]
Hi @warpedgeoid, thanks for reporting!

Indeed, there should be a dependency upon `pcre`, which must have been installed during the `gdal2` bottle build. Apparently `pcre` 8.39 is installed by default on the Travis CI macOS 10.12 image, where the bottles are built. 

The problem stems from GDAL's opportunistic configure behavior, where it grabs anything it can find, in this case PCRE, for [SQLite driver REGEXP operator support](http://gdal.org/drv_sqlite.html).

Fixed in ca646de. Waiting on build and new bottle from Travis output. Thanks!
