### ISSUE TITLE
qgis2 2.18.6 fails to build on Sierra

### ISSUE THREAD

**Issue by pascaloettli** [OSGeo/homebrew-osgeo4mac#227]
Installation of qgis2 2.18.6 fails on Sierra (Version 10.12.4) with an `Error 2`:

    ==> Upgrading osgeo/osgeo4mac/qgis2
    ==> Downloading https://github.com/qgis/QGIS/archive/final-2_18_6.tar.gz
    Already downloaded: /Users/oettli/Library/Caches/Homebrew/qgis2-2.18.6.tar.gz
    ==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cella
    ==> make
    (skip lines)
    [ 96%] Built target qgis_app
    make: *** [all] Error 2

**Comment by dd-a** [comment]
Same here.

**Comment by harsha5500** [comment]
Same here.

==> Upgrading 1 outdated package, with result:
osgeo/osgeo4mac/qgis2 2.18.6
==> Upgrading osgeo/osgeo4mac/qgis2 
==> Downloading https://github.com/qgis/QGIS/archive/final-2_18_6.tar.gz
Already downloaded: /Users/harsha/Library/Caches/Homebrew/qgis2-2.18.6.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis2/2.18.6 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_T
==> make
Last 15 lines from /Users/harsha/Library/Logs/Homebrew/qgis2/02.make:
In file included from /tmp/qgis2-20170412-19908-1yheksj/QGIS-final-2_18_6/src/core/composer/qgscomposeritem.h:23:
In file included from /tmp/qgis2-20170412-19908-1yheksj/QGIS-final-2_18_6/src/core/qgsmaprenderer.h:26:
In file included from /tmp/qgis2-20170412-19908-1yheksj/QGIS-final-2_18_6/src/core/qgsrectangle.h:26:
/tmp/qgis2-20170412-19908-1yheksj/QGIS-final-2_18_6/src/core/qgspoint.h:23:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/composer/moc_qgscomposermap.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/composer/moc_qgscomposermapgrid.cxx.o] Error 1
1 error generated.
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/composer/moc_qgscomposermapitem.cxx.o] Error 1
make[1]: *** [src/core/CMakeFiles/qgis_core.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
QGIS2 - could not load "processing" plugin https://github.com/OSGeo/homebrew-osgeo4mac/issues/203
QGIS2 build fails in pyqt-qt4 make https://github.com/OSGeo/homebrew-osgeo4mac/issues/209

**Comment by dakcarto** [comment]
Hi @pascaloettli, @dd-a and @harsha5500, thanks for reporting!

@pascaloettli and @dd-a, please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

@harsha5500 that looks like enough for me to try and replicate.

Thanks!

**Comment by pascaloettli** [comment]
Hi @dakcarto 

Here it is:
https://gist.github.com/4cdfaf5ee58225caa7276d1b214fdf41

Thank you.

**Comment by dd-a** [comment]
Hi @dakcarto,
My yesterday's troubleshooting logs : https://gist.github.com/bcdd0731c01d6b5f4b2950921439124d useless now since the last update fixed the issue for me too.  
Many thanks !

**Comment by dakcarto** [comment]
Hi, @harsha5500.

I am unable to replicate your build error. Can please you provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs?

**Comment by m-kuhn** [comment]
This seems to be fixed. Please reopen if this happens again and provide the troubleshooting logs.

**Comment by diego-sanchez** [comment]
Hi everyone, 
I am a civil engineering student a complete noobie when it comes to computer programming. I installed QGIS 2.18.2 from the KingChaos website (http://www.kyngchaos.com/software/qgis)

I believe that is the newest version available. I am getting the following errors:

<img width="802" alt="screen shot 2017-04-23 at 8 29 29 pm" src="https://cloud.githubusercontent.com/assets/5333834/25321242/26e71930-286a-11e7-98b5-514dac18be53.png">
<img width="985" alt="screen shot 2017-04-23 at 8 30 15 pm" src="https://cloud.githubusercontent.com/assets/5333834/25321243/26e795cc-286a-11e7-9728-c1f8061f9ffa.png">

Again, I am a complete noobie and not sure what to do. I tried a trick @dakcarto had posted on another thread whereby moving **~/Library/Preferences/org.qgis.QGIS2.plist** to the Desktop and then re-launching QGIS was a quick and dirty fix. Obviously this is not a good fix, since I have to do it every single time before launching QGIS. 

I would greatly appreciate any help! Sorry if my questions are super basic; I literally have very minimal experience with coding or software development. Thanks so very much for your help!
