### ISSUE TITLE
GRASS fails to start - wrong libgeos version

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/homebrew-osgeo4mac#247]
When you open grass in text mode and run g.version, I get:

    dyld: Library not loaded: /usr/local/opt/geos/lib/libgeos-3.6.1.dylib
    Referenced from: /usr/local/Cellar/grass7/7.2.0/grass-7.2.0/bin/g.version
    Reason: image not found
    Abort trap: 6

there is no libgeos-3.6.1:

    ls /usr/local/opt/geos/lib/
    libgeos-3.6.2.dylib	libgeos.dylib		libgeos_c.a		python2.7
    libgeos.a		libgeos_c.1.dylib	libgeos_c.dylib

This is fresh installation of OS Sierra and homebrew

**Comment by pat-s** [comment]
Try reinstalling `grass7` so that it links against the recently updated `geos` (now v3.6.2)

**Comment by petrasovaa** [comment]
Sorry I am not familiar with using homebrew that much, how do I do that? `brew options grass7` doesn't give me `geos` as option.

**Comment by pat-s** [comment]
`brew reinstall grass7`

**Comment by petrasovaa** [comment]
Well, I tried that, but it's still the same problem, nothing has changed in this repository.

**Comment by pat-s** [comment]
try `brew unlink geos && brew link geos && brew reinstall grass7`

**Comment by petrasovaa** [comment]
still the same problem...

**Comment by pat-s** [comment]
do you still have `3.6.1` besides `3.6.2` in `/usr/local/Cellar/geos`?

I had a similar problem after the recent `geos` update but cant exactly remember what I did to solve it. 

Instead of `brew reinstall`, please try also `brew remove grass7 && brew install grass7 && brew link grass7` after having removed any instance of `geos` 3.6.1

**Comment by petrasovaa** [comment]
Still the same. Thanks for working with me on this. I don't have 3.6.1 anywhere, that's what's weird about this.

**Comment by pat-s** [comment]
you start grass in text mode via `grass72 -text`?

Is the GUI startup `grass72` working?

**Comment by petrasovaa** [comment]
You might need to set the homebrew python first:

    export GRASS_PYTHON=python2.7

and then run 

    grass72

You have to create a new location to actually test it

1. create somewhere a directory `grassdata` and browse to it (the top entry field)
2. press _New_ to create new Location, _Next_, then select _Create a generic Cartesian coordinate system`, _Next_, _Finish_, _No_, _OK_ and finally then _Start GRASS session_.
3. now it crashes

**Comment by cmbarton** [comment]
This is not just a HomeBrew issue. I have the same problem when trying to build and run GRASS from the terminal just using dependencies in Anaconda instead of /usr... or /Library/Frameworks. 

I worry that there are hardwire links to standard Linux (and perhaps Mac Frameworks) locations of things that prevent GRASS from finding libraries, headers, etc in other places. 

It doesn't seem to want to link Anaconda libraries as needed. And if I try to start GRASS that has built successfully in an environment without initial paths to Frameworks or /usr...  I get an error message telling me I must use a Framework build of Python. 

So perhaps this needs to go on the GRASS bug list instead of here. 

Michael

**Comment by petrasovaa** [comment]
I realized it installs GRASS from a bottle. So when I use --build-from-source, I am getting errors, basically what is reported in #239. Looking at the log, this error is repeated:

    dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
      Referenced from: /usr/local/opt/gdal2/lib/libgdal.20.dylib
      Reason: image not found
    make[3]: *** [i.landsat.toar.tmp.html] Error 1

I have only `/usr/local/opt/jpeg/lib/libjpeg.9.dylib` on my system.
So the gdal2 bottle is outdated? I tried to recompile gdal2 formula, but I get this problem: #252

So now I am stuck, please advise.

**Comment by petrasovaa** [comment]
This is fixed by 524a5f7, which updates gdal2 formula, now grass can be built from source.

**Comment by cmbarton** [comment]
Is this a GRASS or Homebrew update?

Michael

**Comment by petrasovaa** [comment]
Homebrew update, this problem was just because of outdated bottles.

**Comment by cmbarton** [comment]
Too bad. I was hoping it might help for Anaconda since I'm getting identical errors.


Michael Barton
