### ISSUE TITLE
GRASS fails to start - missing numpy

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/homebrew-osgeo4mac#248]
When I start GRASS, numpy is missing:

    ...
    import gui_core.wxlibplot as plot
     File "/usr/local/Cellar/grass7/7.2.0/grass-7.2.0/gui/wxpython/gui_core/wxlibplot.py", line 121, in    <module>
     import numpy as np
     ImportError: No module named numpy

After Installing numpy it works:

    brew install numpy

But if I understood the formula correctly, it should install automatically with GRASS since it is a dependency?

**Comment by pat-s** [comment]
this might be caused by the recent move of `homebrew/science/numpy` to `homebrew/core/numpy` - but thats just a guess :)

**Comment by dakcarto** [comment]
Hi @petrasovaa, thanks for reporting!

I can only guess that at some point after installing `grass7` you removed `numpy`, or more likelky because GRASS could no longer _find_ `python` because it is now only `python2` (a recent Homebrew change); otherwise, the formula would not install without it...

The dependency for external Python modules is (or was) like:

```
depends_on "numpy" => :python
```

which translates to a recommended module for the given language in `brew info grass7`
```
==> Requirements
Required: unlinkedgrass7 ✘, python ✔, numpy (python module) ✔, x11 ✔
```

This means the formula will fail if the module is not available during install, but _will not install the module_. However, new Homebrew policy is that such modules should be 'vendored' (installed locally within a formula's install prefix). This is similar to Python virtual environments, ensuring each module is correctly versioned for the formula and that users do not need to install the modules outside of Homebrew, e.g. with `pip2`.

This is not such a simple thing to do for large quantity Python dependencies, like `qgis*` formulae.

I think the thing to do going forward is to look into setting up `requirements.txt` for `pip2` and use it to install Python packages, either in a virtual environ or vendored prefix.

Either way, the `grass7` formula should be fixed with regards to the `python2` change in 81423db.

**Comment by petrasovaa** [comment]
Thanks for explaining and the fix. Since this is a more complex problem, I will just close this issue.
