### ISSUE TITLE
qgis2 --with-qspatialite fails to install

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#254]
I've got a make error on `make install` step.
```
CMake Error at src/providers/spatialite/qspatialite/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/tmp/qgis2-20170809-55244-1ijms1m/QGIS-final-2_18_10/build/PlugIns/qgis/sqldrivers/libqsqlspatialite.dylib"
  to
  "/usr/local/Cellar/qt-4/4.8.7/plugins/sqldrivers/libqsqlspatialite.dylib".
```
Full logs here:
https://gist.github.com/94ee6441fdf40b7cea918930c0f8f194

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for reporting!

The `qgis*` formulae have not yet been updated to work with those dependencies (or sandboxing). Working on that today. They will be broken until fixes are applied.

Not quite sure how to fix the `libqsqlspatialite.dylib` install to `qt-4` shared directory at this time, since it requires the `qgis2` formula to be linked, in order to overcome sandboxing constraints.

Also, it appears that the `libqsqlspatialite.dylib` is not correctly linked. That will need fixed as well.

**Comment by dakcarto** [comment]
@nextstopsun, can you try with latest `qgis2`? Thanks!

**Comment by dakcarto** [comment]
@nextstopsun did you get a chance to retry this?

**Comment by nextstopsun** [comment]
@dakcarto Yep, just built `qgis2` without problems. Thanks, @dakcarto. Aside from that, do you have both `qgis2` and `qgis3-dev` on the same machine? Do they get along well? Any special tricks for that?

**Comment by dakcarto** [comment]
> Aside from that, do you have both qgis2 and qgis3-dev on the same machine? Do they get along well? Any special tricks for that?

I do have both installed, actually, `qgis2-ltr`, `qgis2` and `qgis3-dev` and multiple other custom dev builds from inside Qt Creator. Just don't run multiple QGIS 2 installs simultaneously. Definitely no issues between QGIS 2 and 3 running at the same time, as they are quite isolated from each other (with regards to binaries and settings).

Are you having issues with this?
