### ISSUE TITLE
gdal2 fails to configure

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#260]
I get a strange error when running `brew upgrade gdal`

```
checking build system type... x86_64-apple-darwin16.7.0
checking host system type... x86_64-apple-darwin16.7.0
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/gdal2-20170813-29505-17ynsnc/gdal-2.2.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

I'm not cross compiling and info on gdal2 formula says: 
```
/usr/local/Cellar/gdal2/2.2.1 (243 files, 46MB)
  Built from source on 2017-08-09 at 21:12:09 with: --with-complete --with-qhull --with-opencl --with-armadillo --with-mdb --with-libkml --with-sfcgal --with-postgresql --with-mysql
```
So it wasn't cross compiled before also.
Where's the catch here?:)

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for reporting (as always)!

I ran into this when one of the dependencies was building off a different C++ standard lib, e.g. building against GCC instead of clang (new `pdfium-gdal2` formula). Check the deps and see which one may be doing this (you'll need to run `otool -L` on the binaries to see which std lib is linked to). If you find one, try removing that build option and try again.

Thanks!

**Comment by nickrobison** [comment]
I ran into this issue as well, it turned out I had a dependency that was failing to link against and older library that was missing. If you look at the output of your configure.log file, that should give you a pointer in the right direction.

**Comment by nextstopsun** [comment]
My case was fixed by adding path to homebrew `icu4c` to `.bash_profile`.
