### ISSUE TITLE
qgis custom widgets are not installed at the right place

### ISSUE THREAD

**Issue by 3nids** [OSGeo/homebrew-osgeo4mac#279]
qgis custom widgets are installed as follows
>  /usr/local/Cellar/qgis2/2.18.13/lib/qt-4/plugins/designer/libqgis_customwidgets.2.18.13.dylib
/usr/local/Cellar/qgis2/2.18.13/lib/qt-4/plugins/designer/libqgis_customwidgets.dylib
/usr/local/Cellar/qgis2/2.18.13/lib/qt-4/python2.7/site-packages/PyQt4/uic/widget-plugins/qgis_customwidgets.py
also in 
> /usr/local/lib/qt-4/plugins/designer/libqgis_customwidgets.2.18.13.dylib
/usr/local/lib/qt-4/plugins/designer/libqgis_customwidgets.dylib

but I think it should be in /usr/local/Cellar/qt-4/4.8.7/plugins/designer/

**Comment by dakcarto** [comment]
Hi Denis, thanks for reporting!

Recent changes in Homebrew core functionality, specifically sandboxing, disallow writing files into another formula's install prefix, i.e. `/usr/local/Cellar/qt-4/4.8.7/*` is off limits.

However, one can utilize the 'standard' directories that are auto-symlinked by Homebrew, during the `brew link` operation, to install components to a shared location, e.g. `lib`, `bin`, `etc`, etc.

The shared location symlinking can be seen with `/usr/local/lib/qt-4/plugins/designer/` contents:
```console
libqgis_customwidgets.2.18.11.dylib -> ../../../../Cellar/qgis2/2.18.11/lib/qt-4/plugins/designer/libqgis_customwidgets.2.18.11.dylib
libqgis_customwidgets.dylib -> ../../../../Cellar/qgis2/2.18.11/lib/qt-4/plugins/designer/libqgis_customwidgets.dylib
```

Essentially, nothing is 'installed' into `/usr/local/lib/qt-4/*` only symlinked by Homebrew.

Since Qt4 is deprecated and fully removed from Homebrew, I had to devise a means of installing/symlinking the `*-qt4` formulae into `/usr/local`, i.e. not just leaving them isolated in keg-only prefixes. This is the point of `/usr/local/lib/qt-4/*`, which leverages Homebrew auto-symlinking for anything in `<formula prefix>/lib`.

The shared `/usr/local/lib/qt-4/[plugins|python2.7]` subdirectories are then locations that can be referenced by applications, Qt Designer ([as seen here](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qt-4.rb#L131-L135)) and Python, respectively.

I realize this is not ideal, as it requires additional configuration for client applications.

**Comment by 3nids** [comment]
Hi Larry,
Thanks a lot for your detailed explanations.

Everything seems to be setup properly here, but I am not getting the custom widgets in designer.

The only way I found, thanks to your explanations, was to run:
`QT_PLUGIN_PATH=/usr/local/lib/qt-4/plugins /usr/local/Cellar/qt-4/4.8.7/Designer.app/Contents/MacOS/Designer`

**Comment by Gustry** [comment]
Can you add that in the readme.md?

**Comment by dakcarto** [comment]
@3nids wrote:
> The only way I found, thanks to your explanations, was to run:
> QT_PLUGIN_PATH=/usr/local/lib/qt-4/plugins /usr/local/Cellar/qt-4/4.8.7/Designer.app/Contents/MacOS/Designer

Hmm. That's odd. I definitely have no issues here, except maybe that the non-versioned library symlink causes double loading of the library in Designer (see Designer -> About Plugins menu item).

Can you check two things?
1. That indeed `/usr/local/opt/qt-4/Designer.app/Contents/Info.plist` has the following (as it should [from this update](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/qt-4.rb#L131-L135)):
    
```xml
<key>LSEnvironment</key>
<dict>
  <key>QT_PLUGIN_PATH</key>
  <string>/usr/local/lib/qt-4/plugins</string>
</dict>
```

2. If 1. is OK, then `touch /usr/local/opt/qt-4/Designer.app` may help update the app's `launchd` caching, i.e. allow double-click launching in Finder _without_ the QT_PLUGIN_PATH env var needing set.

---

Side note: on macOS, the following is not the way you want to launch .app bundles from the command line:

```
QT_PLUGIN_PATH=/usr/local/lib/qt-4/plugins /usr/local/Cellar/qt 4/4.8.7/Designer.app/Contents/MacOS/Designer
```
That essentially launches _just_ the binary and ignores its bundle characteristics, e.g. the Info.plist is not read. Try the following instead:

```
open /usr/local/opt/qt-4/Designer.app
```
See also: `man open`.

**Comment by dakcarto** [comment]
Second side note:

If you want to launch a .app bundle's internal main binary, you need to create a wrapper script to properly set up the environ, since all of its .app characteristics are ignored.

For example, when launching `qgis2` from the command line, this is utilized (from `/usr/local/opt/qgis2/bin/qgis2` via the formula install):

```
#!/bin/sh

export PATH=/usr/local/opt/qt-4/bin:/usr/local/opt/sip-qt4/libexec/bin:/usr/local/opt/pyqt-qt4/bin:/usr/local/opt/qca-qt4/bin:/usr/local/opt/gdal2-python/bin:/usr/local/opt/gdal2/bin:/usr/local/bin:/usr/local/sbin:/opt/X11/bin:/usr/X11/bin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH
export PYTHONPATH=/usr/local/opt/gdal2-python/lib/python2.7/site-packages:/usr/local/lib/qt-4/python2.7/site-packages:/usr/local/opt/qgis2/libexec/python2.7/site-packages:/usr/local/lib/python2.7/site-packages:$PYTHONPATH
export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins
export GDAL_DATA=/usr/local/opt/gdal2/share/gdal
export GRASS_PREFIX=/usr/local/opt/grass7/grass-base
export OSG_LIBRARY_PATH=/usr/local/lib/osgPlugins-3.5.6
/usr/local/opt/qgis2/QGIS.app/Contents/MacOS/QGIS "$@"
```

This allows one to pass the QGIS command line options as needed, something not so easily done when launching a .app bundle via 'normal' means, e.g. double-clicking.

**Comment by 3nids** [comment]
Thanks a lot for the detailed explanations.
Indeed using `open /usr/local/opt/qt-4/Designer.app` shows the custom widgets in designer.
And yes, Info.plist is as it should be.
