### ISSUE TITLE
`brew info gdal2` plugins caveat mentioning `/usr/local/lib/gdalplugins` is confusing

### ISSUE THREAD

**Issue by vjpr** [OSGeo/homebrew-osgeo4mac#286]
```
Plugins for this version of GDAL/OGR, generated by other formulae, should
be symlinked to the following directory:

  /usr/local/lib/gdalplugins/2.2

You may need to set the following enviroment variable:

  export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins
```

This text references two different dirs for plugins. It is confusing. It it a typo? Or does it look specifically in `gdalplugins/$VERSION`.

- /usr/local/lib/gdalplugins
- /usr/local/lib/gdalplugins/2.2

I had plugins in `gdalplugins` from 1.x and they did not load properly in 2. Maybe this is the purpose of the message?

**Comment by dakcarto** [comment]
Hi @vjpr,

> This text references two different dirs for plugins. It is confusing. It it a typo? Or does it look specifically in gdalplugins/$VERSION.

Yes, [GDAL will look for ABI-compatible plugins](https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdaldrivermanager.cpp#L787-L874) in `${GDAL_DRIVER_PATH}/<major-version>.<minor.version>`, since at least 2 or more years ago (so support for GDAL 1.11 as well).

This means exporting `GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins` will work regardless of whether GDAL 1.11.x or 2.x is being used, as only the plugins from the appropriate ABI-compatible subdirectory will be loaded.

> I had plugins in gdalplugins from 1.x and they did not load properly in 2. Maybe this is the purpose of the message?

Not specifically the purpose of the message. I would not expect GDAL 1.x plugins to load into GDAL 2.x (at least I hope they don't 😃). Plugins can be placed in the base GDAL_DRIVER_PATH directory, however this will lead to unnecessary attempted loading and checking of drivers, relative to the GDAL version used.

Note: several GDAL packaging approaches in the past (including Homebrew) have just installed plugins into the base GDAL_DRIVER_PATH directory. This should no longer be considered an appropriate way of installing plugins in a mixed version environment and should be avoided.
