### ISSUE TITLE
Openjpeg JPEG2000 formula

### ISSUE THREAD

**Issue by kikislater** [OSGeo/homebrew-osgeo4mac#288]
Hi,

With this great news : http://erouault.blogspot.fr/2017/10/optimizing-jpeg2000-decoding.html , I'm surprised that there is no openjpeg formula.
How could we build gdal with openjpeg jpeg2000 support ?

**Comment by dakcarto** [comment]
Hi @kikislater, thanks for reporting!

OpenJPEG 2.3 is supported [in the Homebrew-core tap](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openjpeg.rb). You can build the OpenJPEG driver for `gdal2` by [utilizing the `--with-complete` option](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2.rb#L66-L75):

```
brew install -dv gdal2 --with-complete
```

See `brew info gdal2` or `brew options gdal2` for more generic help about options.

The default 'bottle' of gdal2 is built with no options. Note: adding any options will prompt `brew install` to build from source, instead of using the bottle.

---

Side note: unfortunately, building GDAL/OGR is not very modular, i.e. where all drivers could be built as plugins against a central `libgdal`. This is why so many drivers are grouped under the two general `--with-complete` and `--with-unsupported` options. Otherwise, there would be a _huge_ number of options.

**Comment by kikislater** [comment]
Thank you Larry,
Have to remember how to deal with different jpeg2000 version now (erdas from ecw, jasper and openjepg ...)

**Comment by dakcarto** [comment]
@kikislater wrote:
> Have to remember how to deal with different jpeg2000 version now (erdas from ecw, jasper and openjepg ...)

See [GDAL_SKIP](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_SKIP) environment variable.

**Comment by kikislater** [comment]
Thanks it works !
