### ISSUE TITLE
liblas fails with --with-laszip option

### ISSUE THREAD

**Issue by Ylannl** [OSGeo/homebrew-osgeo4mac#304]
```
CMake Error at cmake/modules/FindLASzip.cmake:94 (MESSAGE):
  Failed to open /usr/local/include/laszip/laszip.hpp file
```

I believe this is due to a change in laszip, since the latest version no longer includes that header file.

**Comment by Ylannl** [comment]
It installs correctly if I manually change the dependency to `laszip@2`. However that one may conflict with the newer `laszip`.

**Comment by nickrobison** [comment]
@Ylannl Glad to hear it's building for you!

Can you clarify your last comment?

> cmake doesn't automatically find this version of liblas.

Do you mean that non-homebred project using cmake are unable to find the liblas headers?

Because homebrew core ships its own versions of gdal and liblas, we can't automatically link the headers into `/usr/local/lib`. There are two workaround though.

1. You can set the include and lib flags to point make to the correct location:
```
    LDFLAGS:  -L/usr/local/opt/liblas-gdal2/lib
    CPPFLAGS: -I/usr/local/opt/liblas-gdal2/include
```

2. You can force link the formula to place the liblas library into `/usr/local/lib`, which should be automatically detected by cmake.

```
brew link --force liblas-gdal2
```

You should _only_ to that know if you know for sure that you don't have any other installed versions of `liblas` or `gdal`. You can add the `--dry-run` flag before hand, to see what might be overwritten.
