### ISSUE TITLE
SagaGisLts fails to install

### ISSUE THREAD

**Issue by stuartE9** [OSGeo/homebrew-osgeo4mac#337]
Installation fails with the errors shown on the attached logs.

[config.log](https://github.com/OSGeo/homebrew-osgeo4mac/files/1866731/config.log)

[03.make.txt](https://github.com/OSGeo/homebrew-osgeo4mac/files/1866732/03.make.txt)

Please let me know if you need further information

Running macOS 10.13.3 on MacBook Pro - mid 2014
2.8 GHz Intel Core i7

**Comment by nickrobison** [comment]
Looks like the issue has to do with a new error in the recent versions of Clang, that was originally a warning. I don't think I'll be able to address the issue without patching their source code.

One workaround would be to have homebrew compile with gcc instead of clang, but that will also required building the SAGA dependencies with gcc as well.

I'm working on a new formula for the latest version of SAGA, which should hopefully resolve this issue, provided the package authors have addressed it.

**Comment by stuartE9** [comment]
Thanks for update.  I appreciate your efforts to fix the problem

Stu

**Comment by nickrobison** [comment]
@stuartE9 With #378 we updated `saga-gis` to the latest version (6.3.0) and we also improved how `saga-gis-lts` works with `qgis2`. Feel free to try them out and let us know if you have any issues.
