### ISSUE TITLE
ecwjp2-sdk fails to install

### ISSUE THREAD

**Issue by aleksandrmelnyk** [OSGeo/homebrew-osgeo4mac#373]
/usr/local/opt/ecwjp2-sdk/lib/libNCSEcw-stdcxx.dylib: no such file

**Comment by nickrobison** [comment]
@aleksandrmelnyk I've updated in the ecwjp2-sdk to the latest version (5.4.0) and resolved the issue you reported. The SDK no longer bundles libstdc++ in the distribution, not sure if that'll be an issue for you or not.

Try `brew update && brew install ecwjp2-sdk` and let me know if the issue is still occurring. Thanks!
