### ISSUE TITLE
Bottles for macOS 10.14 Mojave

### ISSUE THREAD

**Issue by jonathanmccormack** [OSGeo/homebrew-osgeo4mac#480]
From what I can tell, the bots just build one bottle and copy it for both High Serra and Sierra; unfortunately there is no similar Mojave bottle. In the meantime I can build from source, but it'd be good to support macOS 10.14, now that it's been out for a couple of weeks.

**Comment by vincentsarago** [comment]
@jonathanmccormack I was going to work on this, but I have no idea how the bottle are created. I'm currently working on #479 but I'll also love to change the default gdal version from 2.3.1 to 2.3.2 so maybe I can start a PR and we can work together on those issues 

That's said I've some difficulties to compile GDAL right now but I believe it's because of the C++ version which I'd love to add more info directly in the formula. If you have some pro-tip I'll be happy to right them in the formula :-)

**Comment by nickrobison** [comment]
@jonathanmccormack Apologies for the delayed response to this. This should be resolved in e9b654a. We'll be rebuilding formulae as we go, please let me know if you run into any other issues.
