### ISSUE TITLE
grass7 --with-liblas configure error 

### ISSUE THREAD

**Issue by nextstopsun** [OSGeo/homebrew-osgeo4mac#507]
When trying to build grass7 formula `--with-liblas` I get a configure error:
```
checking whether to use libLAS... yes
checking for liblas-config... /usr/local/opt/liblas-gdal2/bin/liblas-config
checking for liblas/capi/liblas.h... yes
configure: error: *** Unable to locate libLAS library.
```

Does anyone else have the same problem?

**Comment by fjperini** [comment]
@nextstopsun I will check this

**Comment by nickrobison** [comment]
@nextstopsun This issue should be resolved. I rebuilt the liblas bottle to link against the latest version of gdal.

**Comment by nextstopsun** [comment]
@nickrobison still same error here

**Comment by nickrobison** [comment]
@nextstopsun Sorry for not getting to this sooner. I can replicate the issue on a new Sierra VM when installing `liblas-gdal2` from the bottle, but building from source (using the `--with-laszip`) flag doesn't cause the error. I'll have to dig into this some more.

**Comment by nickrobison** [comment]
@nextstopsun I think the latest bottle rebuild has addressed the issue, it's now working for me on a clean VM.

The larger issue is that `liblas-config` is pulling in the gdal libraries from the cellar and not from its `opt` directory. This means it's really brittle and dependent on the exact version/revision of GDAL that the bottle was linked against. The actual library itself is working, but the GDAL configuration script uses the helper, which tries to pull in a missing library version. I'll have to do some more digging to see where the underlying cause is.

Let me know if you're still having issues. I'll keep this ticket open until I have a more permanent solution.

**Comment by fjperini** [comment]
@nickrobison @nextstopsun This can be closed, I checked to apply the changes in `grass7` to solve #452, and as you say is necessary rebuild in each new version of `gdal2`.

**Comment by nextstopsun** [comment]
I'm still unable to install grass7 with liblas. Now it causes issues on compile stage:
```
Errors in:
/private/tmp/grass7-20190102-8507-p8fzlt/grass-7.4.3/raster/r.in.lidar
/private/tmp/grass7-20190102-8507-p8fzlt/grass-7.4.3/raster3d/r3.in.lidar
/private/tmp/grass7-20190102-8507-p8fzlt/grass-7.4.3/vector/v.out.lidar
/private/tmp/grass7-20190102-8507-p8fzlt/grass-7.4.3/vector/v.in.lidar
```

Full logs [here](https://gist.github.com/5316bb895af2ead27ac0ed0872b5d6a1)

**Comment by nickrobison** [comment]
@nextstopsun I believe I've fixed the issue you reported, I can verify that it's compiling on my machine. I'm unable to test that it works correctly, do you have a link for a test file that we could include in the formula?

Let me know if you're still running into issues.

**Comment by nextstopsun** [comment]
Seem to be solved, thanks a lot!
