### ISSUE TITLE
gdal2 from bottle cannot read netcdf file

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/homebrew-osgeo4mac#530]
but it can with --with--complete switch.

Wondering if we need that --with-complete switch at all? Why we do not build support for as many formats as possible and have this switch? Are you for its removal?

**Comment by PeterPetrik** [comment]
@fjperini @nickrobison what is your opinion of removal of that --with-complete switch and build the complete version by default? 

I think that right now the gdal2 formula is a bit of mess, since those --with=xyz and --without=xyz are on configure line multiple times with different paths. 

I am happy to fix it if you agree

**Comment by fjperini** [comment]
@PeterPetrik It would be nice to eliminate that switch. But keep in mind that other formulas were created with `gdal2-plugin` reference, I think that because they require another configuration and if they are all included in a single formula it would be more complex than it is.

As for `--with = xyz` and `--without = xyz`, I think there are no references to the same paths, in fact the `--without` do not include path; On the other hand, they should not be changed if only the switch is removed.

You can make the changes to see how it turns out, sure @nickrobison can tell you more.

**Comment by nickrobison** [comment]
@PeterPetrik I would agree with @fjperini we should look into creating a `gdal2-netcdf` bottle, to enable expanded support for additional files.

The reason for not enabling all possible options, is to both reduce the size and installation time, as well as limit the surface area for upstream formula changes breaking the bottles. If it seems like `netcdf` is a common format that's used in the majority of cases, I would definitely support enabling the flag by default.

**Comment by fjperini** [comment]
we close this issue.
if necessary, we can reopen it
