### ISSUE TITLE
grass7 with python3

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/homebrew-osgeo4mac#568]
We use bundled Python3 in our one-click Mac QGIS installer. However it looks like that grass7 depends on python2 and in grass74 script is sets GRASS_PYTHON to python2 too, which is not present in the bundle (and even not sure if technically possible to bundle both). 

related https://github.com/lutraconsulting/qgis-mac-packager/issues/50
https://lists.osgeo.org/pipermail/grass-dev/2018-December/090735.html

**Comment by fjperini** [comment]
@PeterPetrik GRASS in its stable version is not yet compatible with Python 3. But I made some changes to be compatible when using `qgis3`. Everything seems to work correctly #452

You would need to build `grass7` with `python3`, we could do this using a flag `--with-python3` and so that next to the `-HEAD` option you can have what you need.

Only after 7.8/8.0 will they launch the changes for compatibility with Python 3.

**Comment by neteler** [comment]
> Only after 7.8/8.0 will they launch the changes for compatibility with Python 3.

Confirmed, see also
* https://trac.osgeo.org/grass/wiki/Python3Support#Howtotest
* https://lists.osgeo.org/pipermail/grass-dev/2018-December/090789.html

**Comment by luispuerto** [comment]
>You would need to build grass7 with python3, we could do this using a flag --with-python3 and so that next to the -HEAD option you can have what you need.

@fjperini `grass7` doesn't have any flag to build `--with-python3` or I'm missing something here? 

Doesn't qgis3 formula install grass as a dependency with python 3?

**Comment by fjperini** [comment]
@luispuerto I thought I would add that flag. But, it will be better to wait for the version 7.8.

**Comment by nickrobison** [comment]
I would agree with @fjperini, I'd rather not add an unsupported flag to the formula, once 7.8 comes out, we can add and test it.
