### ISSUE TITLE
I can not install postgis in any of the postgres versions (@ 10 and 11).

### ISSUE THREAD

**Issue by luispuerto** [OSGeo/homebrew-osgeo4mac#813]
_This was originally posted by @miguelangelperg in https://github.com/OSGeo/homebrew-osgeo4mac/issues/769#issuecomment-470257463_ 

-------

Hi @fjperini, @luispuerto 

I can not install postgis in any of the postgres versions (@ 10 and 11).

```
# select postgis_full_version() ;
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
CONTEXT:  SQL statement "SELECT public.postgis_lib_version()"
PL/pgSQL function postgis_full_version() line 25 at SQL statement
```
```
# ALTER EXTENSION postgis UPDATE;
ERROR:  could not open extension control file "/usr/local/Cellar/postgresql@10/10.6_1/share/postgresql@10/extension/postgis.control": No such file or directory   
```

My postgis facilities for almost two years have been obtained from the tap osgeo4mac.

   1. Before the upgrade to qgis 3.4.2 I had in my Cellar: postgis and within postgis the different versions: 2.4.4_1 and the linked 2.5.0. Both versions built against gdal version 2.
My GDAL was in my Cellar in the gdal folder. Inside it, were the different versions that had been installed: 2.3.1_1 and 2.3.1_2 (linked).
Postgis without problems

I do not know if it's related, but:

2. After the upgrade, I keep the previous Cellar, which are still linked. But I also have:
postgis2 with version 2.5.1_1
gdal2 with version 2.4.0

If I request: `brew uninstall postgis`
I get:
```
$ brew uninstall postgis

Error: Refusing to uninstall /usr/local/Cellar/postgis/2.5.0
because it is required by postgis2, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies postgis
```

I uninstalled postgis, and linked postgis2, but it does not solve anything. 
I can send details of the experience if it was useful

**Comment by miguelangelperg** [comment]
Hi @luispuerto, @fjperini, thanks
All installed from osgeo4mac tap except *R* and *cairo* (from r_sethrfore) Other taps in my /Homebrew/Library/:  
- /brewsci/homebrew-bio/
- /brewsci/homebrew-science/
- /homebrew/

A partial picture of my situation. I would really appreciate your help

![upgrade_pg3](https://user-images.githubusercontent.com/42784270/53955965-a2ce7b80-40da-11e9-9476-8eadc2f40a5e.jpg)

**Comment by luispuerto** [comment]
I meant a complete new issue, this was closed and **opened by me by mistake**... but doesn't matter.

**Comment by miguelangelperg** [comment]
Thanks @luispuerto

**Comment by fjperini** [comment]
@miguelangelperg I will try to resolve the conflicts between the formulas this weekend.

I will need you to help me make a map of all the dependencies and their dependencies.

**Comment by fjperini** [comment]
If we are going to replace the ones that are in `core`, we need to have all the secondary dependencies in the repository.

For example: `pdal` depends on the `core/gdal`. To build `pdal` with our `osgeo4mac/gdal` version.

**Comment by miguelangelperg** [comment]
Thanks guys. Regards

**Comment by miguelangelperg** [comment]
@fjperini, You said:
```
I will need you to help me make a map of all the dependencies and their dependencies.
```
Of course, you can count on me. Thanks

**Comment by miguelangelperg** [comment]
Hi. I would like to know if I have understood correctly the issue around postgis and gdal.

I thought I understood that:
1. The formulas for the current versions of postgis (2.5.1) and gdal (2.4.0) are called postgis and gdal by default.
2. We need to compile postgis and gdal with options that homebrew-core does not contemplate. This is very nice!
3. Since we can not use the same names for the formulas, we call them postgis2 and gdal2. Very well.

I imagine that Homebrew will also be informed that gda2 = gdal and postgis2 = postgis so that when we install any application that has a postgis or gdal requirement, it can find those requirements in our postgis2 and gdal2.

Because, I can imagine that if Homebrew does not recognize that gda2 = gdal and postgis2 = postgis, then, it is very probable, that homebrew will end up installing postgis and gdal and you having in Cellar: postgis, postgis2, gdal, gdal2.

**Comment by fjperini** [comment]
@miguelangelperg Sure, we have our own versions because the `hombere-core` do not include many of the additional supports.

And since having formulas with the same name causes more problems than benefits, it is better to have them with another name.

The important thing here is to have all the dependencies that we need built with our formulas and to make sure that ours are linked, in this way, Homebrew will use them as predetermined.

The problems you are having are due to conflicts with dependencies that were not created with our versions and that are linked.

A simple example of this:

if we install `pdal`, as it currently uses `homebrew/core/gdal`, it will use that version, and that can bring many conflicts as you imagine.

That is why we need to have all the dependencies built with our versions and that the user be in charge of linking them correctly.

**Comment by fjperini** [comment]
@miguelangelperg That's why we have our version of PostGIS. As for the problem you have: can not you install it?

Maybe it is because it is necessary to rebuild `gdal2` with the new version of PostgreSQL (or v10 if you need it, maybe for this in `gdal2` we have to use a flag to use `postgresql@10`) and then rebuild `postgis2`.

**Comment by fjperini** [comment]
In summary:
- we must have in the repo all formulas that homebrew does not provide additional supports (eg: `gdal`)
- all secondary dependencies must be built (eg: `postgis`, `pdal`) with these new "duplicate" formulas (eg: `gdal2`). Renaming them previously (eg: `postgis2`)
- we have to link them correctly to use them.

**Comment by miguelangelperg** [comment]
Hi @fjperini. Thank you. I'm sorry I could not answer before.

Yes, I can not install postgis through create extension.
I have both versions (10 and 11) I can not install it on any one using this method.
Why do I have two versions? I need them to be able to upgrade from one version to another. Pg_upgrade requires (among other things) that postgis is installed on both versions.

It is possible that the error may be in gdal, but in my cellar I have several gdal (see previous message diagram). Why? Postgres and postgis have been installed from the tap osgeo4mac. R, from the tap sethrfore (I followed the instructions of @luispuerto) When installing R packages, could something be installed? Can I need an application of another tap that has between its postgis or gdal requirements? It may be, I do not know.

But in any case, if in these processes gdal or postgis is reinstalled it will be because its presence in the system has not been detected. What should I do to prevent it from happening that way?

I always want to use the same gdal, of course and I trust the tap. How can I solve the mess that seems to have in my formulas and end up having a single postgis and gdal?

I would really appreciate the help

**Comment by fjperini** [comment]
@miguelangelperg The solution for this is, as I mentioned earlier, having all the main and secondary dependencies in this repository and linking them correctly.

Finally you could delete all those that correspond to `homebrew-core`, they will no longer be used.

This is what we should do:

- 1 - We must have in the repository all the formulas that Homebrew does not provide additional support (for example: `gdal`)
- 2 - All secondary dependencies must be built (for example: `postgis`, `pdal`) with these new "duplicate" formulas (for example: `gdal2`). Renaming previously (for example: `postgis2`)
- 3 - We have to link them correctly to use them.
- 4 - Uninstall the ones that come from  `homebrew-core` (for example: `gdal`, `postgis`), we must make sure to have all of 1-2 so that they do not reinstall those of `homebrew-core`.

And rebuild PostGIS with the version of PostgreSQL you want.

**Comment by miguelangelperg** [comment]
Hi @fjperini 
Dependencies 
```
$ brew uninstall gdal
Error: Refusing to uninstall /usr/local/Cellar/gdal/2.3.1_2
because it is required by osm2pgrouting, pgrouting, postgis and qgis, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies gdal
```

```
$ brew uses --installed gdal
osgeo/osgeo4mac/qgis                     pgrouting
osm2pgrouting                            postgis
```

**Comment by miguelangelperg** [comment]
And .. for **postgis**
```
brew uses --installed postgis
osgeo/osgeo4mac/postgis2   osm2pgrouting              pgrouting
```
For **gdal2**
```
l$ brew uses --installed gdal2
osgeo/osgeo4mac/gdal2-python             osgeo/osgeo4mac/ossim
osgeo/osgeo4mac/grass7                   osgeo/osgeo4mac/postgis2
osgeo/osgeo4mac/openscenegraph-qt5       osgeo/osgeo4mac/qgis
osgeo/osgeo4mac/orfeo6                   osgeo/osgeo4mac/saga-gis-lts
```

For **postgis2**
```
$ brew uses --installed postgis2
osgeo/osgeo4mac/qgis
```

**Comment by miguelangelperg** [comment]
Now in my ```/usr/local/Cellar/``` there are:
-  gdal2   
-  gdal2-python
-  postgis2

**Comment by miguelangelperg** [comment]
running ```brew cleanup```:
```
==> Summary
🍺  /usr/local/Cellar/texinfo/6.6: 404 files, 7.3MB
Removing: /usr/local/Cellar/texinfo/6.5... (403 files, 8.2MB)
Error: Formulae found in multiple taps: 
       * osgeo/osgeo4mac/hdf4
       * brewsci/science/hdf4

Please use the fully-qualified name e.g. osgeo/osgeo4mac/hdf4 to refer the formula.
```

**Comment by miguelangelperg** [comment]
```
$ brew uninstall postgis2
Uninstalling /usr/local/Cellar/postgis2/2.5.1_1... (264 files, 26.5MB)
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  insighttoolkit
  ghostscript
  openscenegraph-qt5
```
Sorry for the clumsiness, because I thought that if I did now: ```brew install postgis```
I would install postgis2.
But it's not like that. I have ** postgis ** again in my Cellar. Also **gdal**

```
$ brew install postgis
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (osgeo/osgeo4mac).
No changes to formulae.

==> Installing dependencies for postgis: cfitsio, hdf5, netcdf, libidn, podofo, glib, pixman, poppler, xerces-c, zstd and gdal
==> Installing postgis dependency: cfitsio
==> Downloading https://homebrew.bintray.com/bottles/cfitsio-3.450_1.mojave.bott
######################################################################## 100.0%
==> Pouring cfitsio-3.450_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/cfitsio/3.450_1: 17 files, 3.2MB
==> Installing postgis dependency: hdf5
==> Downloading https://homebrew.bintray.com/bottles/hdf5-1.10.5.mojave.bottle.t
######################################################################## 100.0%
==> Pouring hdf5-1.10.5.mojave.bottle.tar.gz
Warning: hdf5 dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/hdf5/1.10.5: 256 files, 14.7MB
==> Installing postgis dependency: netcdf
==> Downloading https://homebrew.bintray.com/bottles/netcdf-4.6.2_1.mojave.bottl
######################################################################## 100.0%
==> Pouring netcdf-4.6.2_1.mojave.bottle.tar.gz
Warning: netcdf dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/netcdf/4.6.2_1: 85 files, 6.2MB
==> Installing postgis dependency: libidn
==> Downloading https://homebrew.bintray.com/bottles/libidn-1.35.mojave.bottle.t
######################################################################## 100.0%
==> Pouring libidn-1.35.mojave.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/libidn
==> Summary
🍺  /usr/local/Cellar/libidn/1.35: 72 files, 1.4MB
==> Installing postgis dependency: podofo
==> Downloading https://homebrew.bintray.com/bottles/podofo-0.9.5_2.mojave.bottl
######################################################################## 100.0%
==> Pouring podofo-0.9.5_2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/podofo/0.9.5_2: 152 files, 4.5MB
==> Installing postgis dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.60.0.mojave.bottle.t
######################################################################## 100.0%
==> Pouring glib-2.60.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.60.0: 432 files, 15.3MB
==> Installing postgis dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.38.0.mojave.bottle
######################################################################## 100.0%
==> Pouring pixman-0.38.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pixman/0.38.0: 13 files, 1.3MB
==> Installing postgis dependency: poppler
==> Downloading https://homebrew.bintray.com/bottles/poppler-0.74.0.mojave.bottl
######################################################################## 100.0%
==> Pouring poppler-0.74.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/poppler/0.74.0: 458 files, 24.5MB
==> Installing postgis dependency: xerces-c
==> Downloading https://homebrew.bintray.com/bottles/xerces-c-3.2.2.mojave.bottl
######################################################################## 100.0%
==> Pouring xerces-c-3.2.2.mojave.bottle.1.tar.gz
🍺  /usr/local/Cellar/xerces-c/3.2.2: 1,687 files, 36.8MB
==> Installing postgis dependency: zstd
==> Downloading https://homebrew.bintray.com/bottles/zstd-1.3.8.mojave.bottle.ta
######################################################################## 100.0%
==> Pouring zstd-1.3.8.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/zstd/1.3.8: 27 files, 2.9MB
==> Installing postgis dependency: gdal
==> Downloading https://homebrew.bintray.com/bottles/gdal-2.4.0_1.mojave.bottle.
######################################################################## 100.0%
==> Pouring gdal-2.4.0_1.mojave.bottle.tar.gz
Warning: gdal dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/gdal/2.4.0_1: 304 files, 58.7MB
==> Installing postgis
==> Downloading https://homebrew.bintray.com/bottles/postgis-2.5.1.mojave.bottle
######################################################################## 100.0%
==> Pouring postgis-2.5.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/postgis/2.5.1: 263 files, 26.6MB
==> Caveats
==> libidn
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/libidn

$ 
```
After  ```brew uninstall postgis gdal```  and  ```brew cleanup```,

Reinstall postgis2 and now In my system is only **posgis2** and **gdal2**

Now, if I install an R package that has a postgis or gdal requirement, R will be able to recognize that I have the required postgis or gdal version available on my system? or it will not, and will install a new postgis or a new gdal ?.

Is it possible that this happens? If so, how should I handle this?

**Comment by fjperini** [comment]
Thanks for reporting the dependencies you have installed from `homebrew-core`.

If you uninstalled the `homebrew-core` dependencies and did not install any other packages, they should not be installed. It is possible that you have installed one that requires the `homebrew-core` versions.

As for R, I think not, although it will depend on how and what installed.

We will change the name of all the formulas and we will bring those that depend on GDAL, among others.
Then, everyone will have to clean their Homebrew, uninstalling the ones that were replaced by these new ones. This step is central, if you reinstall those that are in `homebrew-core` and link them, the problem will persist. Therefore, we must have all the necessary dependencies so that the user does not install them from `homebrew-core`.

We will have to make a list of all the dependencies that we use and that should be installed from this tap.

**Comment by fjperini** [comment]
Here is an example of the dependencies you reported:

> brew uses --installed postgis
> osgeo/osgeo4mac/postgis2   osm2pgrouting              pgrouting

We will need to bring this tap: `osm2pgrouting` and `pgrouting`

Because if they are not in this tap, the user will install them from `homebrew-core`, and we will return to the same problem.

**Comment by miguelangelperg** [comment]
@luispuerto, @fjperini 

In R, this happens:

```
> library(rgdal)
Loading required package: sp
Error: package or namespace load failed for ‘rgdal’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/3.5/site-library/rgdal/libs/rgdal.so':
  dlopen(/usr/local/lib/R/3.5/site-library/rgdal/libs/rgdal.so, 6): Library not loaded: /usr/local/opt/gdal/lib/libgdal.20.dylib
  Referenced from: /usr/local/lib/R/3.5/site-library/rgdal/libs/rgdal.so   Reason: image not found
```

As you can see: 
Library not loaded: /usr/local/opt/gdal/lib/libgdal.20.dylib

My libgdal.20.dylib is in:
 /usr/local/opt/gdal2/lib/

Although, it is also in
/usr/local/opt/gdal-20/lib/

**Comment by miguelangelperg** [comment]
@luispuerto, @fjperini
About the above. It seems that gdal2 is not yet recognized as gdal by our system.

```
$ gdalinfo --version
-bash: gdalinfo: command not found
```

So,

```
$ brew link --force gdal2
Linking /usr/local/Cellar/gdal2/2.4.0... 99 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/gdal2/bin:$PATH"' >> ~/.zshrc
```
Then
```
$ gdalinfo --version
GDAL 2.4.0, released 2018/12/14
```
And, in R we will be using gdal2

```
> library(rgdal)
rgdal: version: 1.3-6, (SVN revision 773)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.4.0, released 2018/12/14
   but rgdal build and GDAL runtime not in sync:
   ... consider re-installing rgdal!!
 Path to GDAL shared files: /usr/local/Cellar/gdal2/2.4.0/share/gdal
 GDAL binary built with GEOS: TRUE 
 Loaded PROJ.4 runtime: Rel. 5.2.0, September 15th, 2018, [PJ_VERSION: 520]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.3-1 
```

**Comment by miguelangelperg** [comment]
@luispuerto, @fjperini  **Retrying to enable postgis**.

After relink gdal2 and reinstall postgis2, I try to create the postgis extension in my postgres database.

```
$ psql
psql (11.2)
Type "help" for help.
```

```
# create extension postgis;
ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.5.so": dlopen(/usr/local/lib/postgresql/postgis-2.5.so, 10): Symbol not found: _AllocSetContextCreate
  Referenced from: /usr/local/lib/postgresql/postgis-2.5.so
  Expected in: /usr/local/opt/postgresql/bin/postgres
 in /usr/local/lib/postgresql/postgis-2.5.so
```

```
# ALTER EXTENSION postgis UPDATE TO "2.5.1";
ERROR:  extension "postgis" does not exist
```
The problem should not be in gdal, because:

```
$ gdalinfo --version
GDAL 2.4.0, released 2018/12/14
```

**Comment by fjperini** [comment]
It's what I told you, you need to have our versions linked.
You had installed the GDAL version of `homebrew-core` and it was linked.

You probably have the PostGIS version of `homebrew-core` (`postgis`) installed, or it is linked. Remember, you need to use our version (`postgis2`).
And that is built with the PostgreSQL that you are using. You have to rebuild `postgis2` with the new version of `postgresql` or `postgresql@10`.

I'm about to update all these formulas and bring the others that require these. Of this do you will not need to install those of `homebrew-core` and you will be able to eliminate them as an extra measure to make sure that you are using ours.

**Comment by miguelangelperg** [comment]
@luispuerto, @fjperini -- **A little crazy all for my knowledge**

```
$ brew unlink postgis
Error: No such keg: /usr/local/Cellar/postgis
```
```
$ brew uninstall postgis
Error: No such keg: /usr/local/Cellar/postgis
```
```
$ brew unlink postgis2
Unlinking /usr/local/Cellar/postgis2/2.5.1_1... 227 symlinks removed
```
```
$ brew uninstall postgis2
Uninstalling /usr/local/Cellar/postgis2/2.5.1_1... (264 files, 26.5MB)
```

```
$ brew cleanup
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

  insighttoolkit
  ghostscript
  openscenegraph-qt5
```

```
$ brew install postgis2
==> Installing postgis2 from osgeo/osgeo4mac
==> Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/postgis2-2.5.1_1.mojav
Already downloaded: /Users/miguelmbp/Library/Caches/Homebrew/downloads/9f04968f293b9036b5042a9f53952acc7b6fb3ce7c499173ae9866e87cc82397--postgis2-2.5.1_1.mojave.bottle.tar.gz
==> Pouring postgis2-2.5.1_1.mojave.bottle.tar.gz
==> Caveats
To create a spatially-enabled database, see the documentation:
  https://postgis.net/docs/manual-2.4/postgis_installation.html#create_new_db_extensions
If you are currently using PostGIS 2.0+, you can go the soft upgrade path:
  ALTER EXTENSION postgis UPDATE TO "2.5.1”;

Users of 1.5 and below will need to go the hard-upgrade path, see here:
  https://postgis.net/docs/manual-2.4/postgis_installation.html#upgrading
PostGIS SQL scripts installed to:
  /usr/local/opt/postgis2/share/postgis2
PostGIS plugin libraries installed to:
  /usr/local/lib
PostGIS extension modules installed to:
  /usr/local/share/postgresql/extension
==> Summary
🍺  /usr/local/Cellar/postgis2/2.5.1_1: 264 files, 26.5MB
```

```
$ brew services start postgres
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
```
```
$ psql
psql (11.2)
Type "help" for help.
```
```
# ALTER EXTENSION postgis update;
ERROR:  extension "postgis" does not exist
```
```
# create extension postgis;
ERROR:  could not load library "/usr/local/lib/postgresql/postgis-2.5.so": dlopen(/usr/local/lib/postgresql/postgis-2.5.so, 10): Symbol not found: _AllocSetContextCreate
  Referenced from: /usr/local/lib/postgresql/postgis-2.5.so
  Expected in: /usr/local/opt/postgresql/bin/postgres
 in /usr/local/lib/postgresql/postgis-2.5.so
miguelmbp=# \q
```
**Despite the latest**
```$ brew uninstall postgres
Error: Refusing to uninstall /usr/local/Cellar/postgresql/11.2
because it is required by postgis2, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies postgres
```

> ***Refusing
> to uninstall /usr/local/Cellar/postgresql/11.2
>because it is required by postgis2, which is currently installed***

**Comment by fjperini** [comment]
Well, maybe now you just need to rebuild `gdal2` with the version of PostgreSQL that you want: `postgresql` (it is by default) or `postgresql@10`. And then rebuild `posgis2`.

I'm working to update the formulas and upload those that depend on them.

**Comment by miguelangelperg** [comment]
@fjperini Thank you. 
I'll wait for the important machine, but I could be testing on another machine.
What would be the steps to rebuild ?. Uninstall first postgres, postgis2 and gdal2 and then, how should I reinstall them? Some order installation?

**Comment by fjperini** [comment]
@miguelangelperg If you wait a couple of hours, I'll be updating these formulas, and adding support for v10. Then we'll tell you how to continue.

**Comment by miguelangelperg** [comment]
Ok. Thanks. Good job!

**Comment by miguelangelperg** [comment]
@fjperini  I had thrown it before you asked me to wait Postgis installed on postges11

```brew reinstall -s gdal2 postgis2``` were allowed to create the extension, finally.

```
$ psql
psql (11.2)
Type "help" for help.

# create extension postgis;
CREATE EXTENSION
# select postgis_full_version();
                                                                                          postgis_full_version                                                                                          
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="2.5.1 r17027" [EXTENSION] PGSQL="110" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" GDAL="GDAL 2.4.0, released 2018/12/14" LIBXML="2.9.9" LIBJSON="0.13.1" RASTER
(1 row)
```

**Comment by fjperini** [comment]
Great!

Yes, the problems were due to the fact that you were using the `homebrew-core` versions.

In the updates I will include support for v10.

Remember not to install or have the `homebrew-core` versions linked.

**Comment by fjperini** [comment]
Close these issues, we can open them later if problems arise after updating.

**Comment by kellyfelkins** [comment]
Hello @miguelangelperg - how did you make this amazing visualization? https://github.com/OSGeo/homebrew-osgeo4mac/issues/813#issuecomment-470519984

I love it!

**Comment by kellyfelkins** [comment]
We had a related problem that we solved by *not* using homebrew. We had old postgres/postgis databases that we needed to upgrade to a newer version of postgres. I don't think this is possible with homebrew because, while postgresql is versioned, postgis is not. I was not able to install an older version of postgis via homebrew.

However, [postgres.app](https://postgresapp.com/) made it easy. You can install the multi-version version of postgres.app. All of the versions include postgis. Once installed we were able to open the older data and dump it. Then initialize a newer database and reload.

**Comment by efojs** [comment]
@kellyfelkins it looks very much like www.mindmeister.com

I finally moved to [postgres.app](https://postgresapp.com/).. phew!
